# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'CBTableViewController' do
pod 'MJRefresh'
pod 'MJExtension'
end

target 'CBTableViewControllerTests' do

end

