# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CBTableViewControllerExamples' do
pod 'CBTableViewController', :path=>"../"
pod 'AFNetworking'
end

target 'CBTableViewControllerExamplesTests' do

end

